name: ci
on: 
  push:
    branches:
      - docker
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: build
        run: |
          set -x
          docker build  --tag image:test .
      -
        name: run
        run:  |
          set -x
          docker run --name test --volume ${PWD}/data/words.txt:/data/words.txt image:test
