name: ci
on: 
  push:
    branches:
      - docker
jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: build
        run: |
          set -x
          docker build  --tag image:test .
      -
        name: run
        run:  |
          set -x
          docker run --name test --volume ${PWD}/data/words.txt:/data/words.txt image:test
      -
        name: test
        run:  |
          set -x
          docker logs test 2>& 1 | grep '{1: 0, 2: 80, 3: 805, 5: 4497, 4: 2790, 8: 4821, 7: 5759, 9: 3552, 6: 6246, 11: 1054, 10: 2082, 12: 558, 14: 140, 16: 70, 15: 90, 20: 6, 19: 14, 17: 44, 13: 250, 18: 20, 21: 8, 22: 4, 23: 0, 24: 0}'
          
